name: Label PR Authors (Hourly)

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:     # allow manual trigger too

permissions:
  pull-requests: write
  issues: write

jobs:
  label-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open",
              per_page: 100,
            });

            const INTERNAL_USERNAMES = ["williamlm", "danielnata", "javier", /* etc */];

            for (const pr of prs.data) {
              const labels = pr.labels.map(l => l.name);
              const hasLabel = labels.includes("Maintainer") || labels.includes("Contributor");

              if (hasLabel) continue;

              const author = pr.user.login;
              const isInternal = INTERNAL_USERNAMES.includes(author);

              const label = isInternal ? "Maintainer" : "Contributor";
              console.log(`Labeling PR #${pr.number} by ${author} as ${label}`);

              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                labels: [label],
              });
            }